import type {
  Client,
  CrmUser,
  PipelineStage,
  Product,
  RoleDefinition,
} from "@/lib/amison-crm/types";

const iso = (value: string) => new Date(value).toISOString();
export const crmRoles: RoleDefinition[] = [
  {
    key: "ADMIN",
    label: "Administrador",
    summary: "Control total del CRM, seguridad y parametrizacion.",
    permissions: [
      "dashboard.read",
      "lead.manage",
      "client.manage",
      "contact.manage",
      "opportunity.manage",
      "quote.manage",
      "quote.approve",
      "document.manage",
      "report.read",
      "forecast.read",
      "automation.manage",
      "settings.manage",
      "user.manage",
    ],
  },
  {
    key: "DIRECTOR",
    label: "Direccion",
    summary: "Lectura ejecutiva del pipeline, forecast y rentabilidad.",
    permissions: [
      "dashboard.read",
      "client.manage",
      "opportunity.manage",
      "quote.manage",
      "report.read",
      "forecast.read",
    ],
  },
  {
    key: "SALES_MANAGER",
    label: "Gerente comercial",
    summary: "Gestion integral del proceso comercial y aprobacion de descuentos.",
    permissions: [
      "dashboard.read",
      "lead.manage",
      "client.manage",
      "contact.manage",
      "opportunity.manage",
      "quote.manage",
      "quote.approve",
      "document.manage",
      "report.read",
      "forecast.read",
      "automation.manage",
    ],
  },
  {
    key: "SALES_EXECUTIVE",
    label: "Ejecutivo de ventas",
    summary: "Gestion de cartera, oportunidades, cotizaciones y tareas propias.",
    permissions: [
      "dashboard.read",
      "lead.manage",
      "client.manage",
      "contact.manage",
      "opportunity.manage",
      "quote.manage",
      "document.manage",
      "forecast.read",
    ],
  },
  {
    key: "PRODUCTION",
    label: "Produccion",
    summary: "Consulta de especificaciones tecnicas y oportunidades ganadas.",
    permissions: ["dashboard.read", "document.manage"],
  },
  {
    key: "QUALITY",
    label: "Calidad",
    summary: "Consulta de trazabilidad, certificados y aprobaciones tecnicas.",
    permissions: ["dashboard.read", "document.manage"],
  },
  {
    key: "FINANCE",
    label: "Finanzas",
    summary: "Lectura de condiciones de pago, valores y reportes comerciales.",
    permissions: ["dashboard.read", "quote.manage", "report.read"],
  },
  {
    key: "CUSTOMER_SUCCESS",
    label: "Atencion al cliente",
    summary: "Seguimiento de postventa, reclamos y estado general de clientes.",
    permissions: ["dashboard.read", "client.manage", "document.manage"],
  },
];

export const crmUsers: CrmUser[] = [
  {
    id: "usr-lucia",
    name: "Lucia Mendez",
    email: "lucia.mendez@amison.demo",
    role: "DIRECTOR",
    title: "Direccion comercial",
    territory: "LATAM",
    avatar: "/brand/amison-icon.png",
  },
  {
    id: "usr-martin",
    name: "Martin Ayala",
    email: "martin.ayala@amison.demo",
    role: "SALES_MANAGER",
    title: "Gerente comercial",
    territory: "Argentina",
    avatar: "/brand/amison-icon.png",
  },
  {
    id: "usr-sofia",
    name: "Sofia Rinaldi",
    email: "sofia.rinaldi@amison.demo",
    role: "SALES_EXECUTIVE",
    title: "Ejecutiva de cuentas pharma",
    territory: "AMBA",
    avatar: "/brand/amison-icon.png",
  },
  {
    id: "usr-pablo",
    name: "Pablo Neri",
    email: "pablo.neri@amison.demo",
    role: "SALES_EXECUTIVE",
    title: "Ejecutivo de desarrollo",
    territory: "Interior",
    avatar: "/brand/amison-icon.png",
  },
  {
    id: "usr-elena",
    name: "Elena Costa",
    email: "elena.costa@amison.demo",
    role: "QUALITY",
    title: "Coordinadora de calidad",
    territory: "Planta",
    avatar: "/brand/amison-icon.png",
  },
  {
    id: "usr-gaston",
    name: "Gaston Farina",
    email: "gaston.farina@amison.demo",
    role: "PRODUCTION",
    title: "Jefe de produccion",
    territory: "Planta",
    avatar: "/brand/amison-icon.png",
  },
  {
    id: "usr-irene",
    name: "Irene Pujol",
    email: "irene.pujol@amison.demo",
    role: "FINANCE",
    title: "Finanzas",
    territory: "Backoffice",
    avatar: "/brand/amison-icon.png",
  },
  {
    id: "usr-admin",
    name: "Admin AMISON",
    email: "admin@amison.demo",
    role: "ADMIN",
    title: "Administrador del sistema",
    territory: "Corporativo",
    avatar: "/brand/amison-icon.png",
  },
];

export const crmPipelineStages: PipelineStage[] = [
  { id: "stg-1", name: "Lead recibido", probability: 10, tone: "#274DFF" },
  { id: "stg-2", name: "Contacto inicial", probability: 18, tone: "#2D64FF" },
  {
    id: "stg-3",
    name: "Relevamiento tecnico",
    probability: 28,
    tone: "#2E7BF8",
  },
  {
    id: "stg-4",
    name: "Solicitud de especificaciones",
    probability: 35,
    tone: "#3390F4",
  },
  {
    id: "stg-5",
    name: "Cotizacion en preparacion",
    probability: 48,
    tone: "#3BA6EE",
  },
  {
    id: "stg-6",
    name: "Cotizacion enviada",
    probability: 55,
    tone: "#43B7E7",
  },
  { id: "stg-7", name: "Negociacion", probability: 65, tone: "#4CC8DE" },
  {
    id: "stg-8",
    name: "Muestra / prueba tecnica",
    probability: 72,
    tone: "#59D4C7",
  },
  {
    id: "stg-9",
    name: "Aprobacion de arte / calidad",
    probability: 80,
    tone: "#6DDBAD",
  },
  {
    id: "stg-10",
    name: "Orden de compra solicitada",
    probability: 88,
    tone: "#86E08D",
  },
  { id: "stg-11", name: "Ganada", probability: 100, tone: "#4ADE80" },
  { id: "stg-12", name: "Perdida", probability: 0, tone: "#FB7185" },
  { id: "stg-13", name: "Pausada", probability: 12, tone: "#A1A1AA" },
];

export const crmProducts: Product[] = [
  {
    id: "prd-estuches",
    name: "Estuches plegadizos",
    category: "Estuches plegadizos",
    description:
      "Packaging premium con foco en cumplimiento normativo, terminacion y legibilidad.",
    possibleMaterials: ["Triplex 300g", "Sulfatado 320g", "Cartulina SBS"],
    possibleFinishes: ["Barniz UV", "Hot stamping", "Braille", "Relieve"],
    technicalRequirements: [
      "Control de arte en preprensa",
      "Trazabilidad por lote",
      "Inspeccion visual en linea",
    ],
    quoteFields: ["medidas", "gramaje", "colores", "troquelado", "braille"],
    baseCost: 0.18,
    suggestedMargin: 28,
    estimatedProductionDays: 15,
    documents: ["Ficha tecnica estuche", "Checklist de trazabilidad"],
    active: true,
  },
  {
    id: "prd-prospectos",
    name: "Prospectos medicos",
    category: "Prospectos medicos",
    description:
      "Prospectos de alta densidad de informacion con plegado controlado y lectura optimizada.",
    possibleMaterials: ["Obra 60g", "Biblia 40g", "Obra 70g"],
    possibleFinishes: ["Plegado cruzado", "Plegado acordeon"],
    technicalRequirements: [
      "Control de version documental",
      "Revision de legibilidad",
      "Prueba de plegado",
    ],
    quoteFields: ["medidas", "cantidad de paneles", "gramaje", "colores"],
    baseCost: 0.04,
    suggestedMargin: 24,
    estimatedProductionDays: 10,
    documents: ["Norma interna de plegado"],
    active: true,
  },
  {
    id: "prd-etiquetas",
    name: "Etiquetas autoadhesivas",
    category: "Etiquetas autoadhesivas",
    description:
      "Etiquetas para frascos, ampollas y secondary packaging con lectura por camara.",
    possibleMaterials: ["BOPP blanco", "Papel couche", "PET plata"],
    possibleFinishes: ["Barniz acuoso", "Datos variables", "Control por camara"],
    technicalRequirements: [
      "Registro fino",
      "Lectura de codigo variable",
      "Adhesivo validado",
    ],
    quoteFields: ["medidas", "adhesivo", "datos variables", "control por camara"],
    baseCost: 0.06,
    suggestedMargin: 31,
    estimatedProductionDays: 12,
    documents: ["Plan de control etiqueta"],
    active: true,
  },
  {
    id: "prd-exhibidores",
    name: "Exhibidores",
    category: "Exhibidores",
    description:
      "Piezas POP y exhibidores de alto impacto para lanzamientos y trade marketing pharma.",
    possibleMaterials: ["Microcorrugado", "Carton compacto", "PVC expandido"],
    possibleFinishes: ["Laminado mate", "Troquelado especial", "Montaje"],
    technicalRequirements: [
      "Plano estructural",
      "Prueba de armado",
      "Validacion de resistencia",
    ],
    quoteFields: ["medidas", "cantidad", "estructura", "logistica"],
    baseCost: 1.35,
    suggestedMargin: 34,
    estimatedProductionDays: 18,
    documents: ["Plano estructural base"],
    active: true,
  },
  {
    id: "prd-servicios",
    name: "Servicios especiales",
    category: "Servicios especiales",
    description:
      "Desarrollos a medida, serializacion, lotes cortos y validaciones especiales.",
    possibleMaterials: ["Segun proyecto"],
    possibleFinishes: ["Segun proyecto"],
    technicalRequirements: [
      "Kickoff tecnico",
      "Plan de pruebas",
      "Aprobacion multifuncional",
    ],
    quoteFields: ["alcance", "entregables", "ingenieria", "aprobaciones"],
    baseCost: 5.5,
    suggestedMargin: 38,
    estimatedProductionDays: 20,
    documents: ["Template de alcance"],
    active: true,
  },
];

export const crmClients: Client[] = [
  {
    id: "cli-bionexa",
    legalName: "BioNexa Laboratorios S.A.",
    tradeName: "BioNexa",
    cuit: "30-71234567-1",
    address: "Av. del Libertador 5320, Munro",
    province: "Buenos Aires",
    country: "Argentina",
    phone: "+54 11 4301-2280",
    website: "https://bionexa.demo",
    taxCondition: "IVA Responsable Inscripto",
    type: "laboratorio",
    segment: "Especialidades hospitalarias",
    status: "activo",
    executiveId: "usr-sofia",
    paymentTerms: "45 dias FF",
    usualLeadTime: "15 a 20 dias",
    usualProducts: ["Estuches plegadizos", "Etiquetas autoadhesivas"],
    priorityLevel: "A",
    commercialRisk: "moderado",
    internalNotes: "Cliente estrategico con foco en trazabilidad y cambios frecuentes de arte.",
    lastInteractionAt: iso("2026-06-20T11:30:00"),
    nextAction: "Validar cronograma de muestra para linea oncologica.",
    repurchaseProbability: 84,
    churnRisk: 18,
  },
  {
    id: "cli-pharmadelta",
    legalName: "PharmaDelta Argentina S.R.L.",
    tradeName: "PharmaDelta",
    cuit: "30-70981234-8",
    address: "Ruta 8 km 61, Pilar",
    province: "Buenos Aires",
    country: "Argentina",
    phone: "+54 230 455-8124",
    website: "https://pharmadelta.demo",
    taxCondition: "IVA Responsable Inscripto",
    type: "laboratorio",
    segment: "OTC y consumo masivo",
    status: "activo",
    executiveId: "usr-martin",
    paymentTerms: "30 dias",
    usualLeadTime: "10 a 15 dias",
    usualProducts: ["Estuches plegadizos", "Exhibidores"],
    priorityLevel: "A",
    commercialRisk: "controlado",
    internalNotes: "Muy buen historico de recompra. Sensible a visual merchandising.",
    lastInteractionAt: iso("2026-06-18T09:00:00"),
    nextAction: "Presentar propuesta estacional para campana invierno.",
    repurchaseProbability: 91,
    churnRisk: 12,
  },
  {
    id: "cli-genfarma",
    legalName: "GenFarma Biotech S.A.",
    tradeName: "GenFarma",
    cuit: "30-70119933-5",
    address: "Parque Industrial Garin, lote 12",
    province: "Buenos Aires",
    country: "Argentina",
    phone: "+54 348 442-1911",
    website: "https://genfarma.demo",
    taxCondition: "IVA Responsable Inscripto",
    type: "laboratorio",
    segment: "Biotecnologia",
    status: "activo",
    executiveId: "usr-pablo",
    paymentTerms: "60 dias",
    usualLeadTime: "20 a 25 dias",
    usualProducts: ["Etiquetas autoadhesivas", "Servicios especiales"],
    priorityLevel: "A",
    commercialRisk: "alto",
    internalNotes: "Proceso de calidad muy exigente. Requiere aprobaciones cruzadas.",
    lastInteractionAt: iso("2026-06-16T16:20:00"),
    nextAction: "Compartir plan de control por camara para serializacion.",
    repurchaseProbability: 72,
    churnRisk: 41,
  },
  {
    id: "cli-saludnova",
    legalName: "SaludNova Pharma S.A.",
    tradeName: "SaludNova",
    cuit: "30-70845712-2",
    address: "Colectora Panamericana 3101, Tortuguitas",
    province: "Buenos Aires",
    country: "Argentina",
    phone: "+54 11 5264-7782",
    website: "https://saludnova.demo",
    taxCondition: "IVA Responsable Inscripto",
    type: "laboratorio",
    segment: "Genericos",
    status: "activo",
    executiveId: "usr-sofia",
    paymentTerms: "30 dias FF",
    usualLeadTime: "12 dias",
    usualProducts: ["Prospectos medicos", "Estuches plegadizos"],
    priorityLevel: "B",
    commercialRisk: "moderado",
    internalNotes: "Busca bajar costo sin comprometer compliance.",
    lastInteractionAt: iso("2026-06-21T14:00:00"),
    nextAction: "Revisar opcion de gramaje alternativo para reducir costo.",
    repurchaseProbability: 77,
    churnRisk: 25,
  },
  {
    id: "cli-innovaq",
    legalName: "InnovaQ Pharma S.A.",
    tradeName: "InnovaQ",
    cuit: "30-70533411-0",
    address: "Bv. Los Alemanes 4501, Cordoba",
    province: "Cordoba",
    country: "Argentina",
    phone: "+54 351 501-8822",
    website: "https://innovaq.demo",
    taxCondition: "IVA Responsable Inscripto",
    type: "laboratorio",
    segment: "Lanzamientos y desarrollo",
    status: "prospecto",
    executiveId: "usr-pablo",
    paymentTerms: "Anticipo 50% + saldo contra entrega",
    usualLeadTime: "20 dias",
    usualProducts: ["Servicios especiales", "Exhibidores"],
    priorityLevel: "B",
    commercialRisk: "alto",
    internalNotes: "Cuenta nueva con alto potencial si se gana el desarrollo estructural.",
    lastInteractionAt: iso("2026-06-19T10:15:00"),
    nextAction: "Enviar mockup de exhibidor y plan de aprobaciones.",
    repurchaseProbability: 68,
    churnRisk: 39,
  },
  {
    id: "cli-medicor",
    legalName: "Medicor Labs Argentina S.A.",
    tradeName: "Medicor",
    cuit: "30-71422255-9",
    address: "Calle 9 n. 1340, La Plata",
    province: "Buenos Aires",
    country: "Argentina",
    phone: "+54 221 612-4001",
    website: "https://medicor.demo",
    taxCondition: "IVA Responsable Inscripto",
    type: "laboratorio",
    segment: "Dermocosmetica",
    status: "activo",
    executiveId: "usr-martin",
    paymentTerms: "30/60 dias",
    usualLeadTime: "14 dias",
    usualProducts: ["Etiquetas autoadhesivas", "Exhibidores"],
    priorityLevel: "B",
    commercialRisk: "controlado",
    internalNotes: "Muy buena reaccion a exhibidores de lanzamientos.",
    lastInteractionAt: iso("2026-06-15T17:10:00"),
    nextAction: "Proponer kit completo para nuevo lanzamiento dermo.",
    repurchaseProbability: 81,
    churnRisk: 17,
  },
  {
    id: "cli-vitafor",
    legalName: "Vitafor Argentina S.A.",
    tradeName: "Vitafor",
    cuit: "30-71155100-7",
    address: "Av. Colon 920, Rosario",
    province: "Santa Fe",
    country: "Argentina",
    phone: "+54 341 620-8100",
    website: "https://vitafor.demo",
    taxCondition: "IVA Responsable Inscripto",
    type: "laboratorio",
    segment: "Suplementos y bienestar",
    status: "activo",
    executiveId: "usr-sofia",
    paymentTerms: "Cheque 45 dias",
    usualLeadTime: "12 a 18 dias",
    usualProducts: ["Estuches plegadizos", "Prospectos medicos"],
    priorityLevel: "B",
    commercialRisk: "moderado",
    internalNotes: "Buena estacionalidad, seguimiento activo en lanzamientos.",
    lastInteractionAt: iso("2026-06-22T12:45:00"),
    nextAction: "Preparar forecast de campana primavera.",
    repurchaseProbability: 79,
    churnRisk: 24,
  },
  {
    id: "cli-laboris",
    legalName: "Laboris Farma S.A.",
    tradeName: "Laboris",
    cuit: "30-71999221-6",
    address: "Parque industrial Perez, nave 5",
    province: "Santa Fe",
    country: "Argentina",
    phone: "+54 341 610-4420",
    website: "https://laboris.demo",
    taxCondition: "IVA Responsable Inscripto",
    type: "laboratorio",
    segment: "Veterinaria",
    status: "inactivo",
    executiveId: "usr-pablo",
    paymentTerms: "30 dias",
    usualLeadTime: "15 dias",
    usualProducts: ["Etiquetas autoadhesivas"],
    priorityLevel: "C",
    commercialRisk: "alto",
    internalNotes: "Sin contacto comercial hace 65 dias.",
    lastInteractionAt: iso("2026-04-18T11:00:00"),
    nextAction: "Campana de recuperacion con propuesta de reevaluacion de costos.",
    repurchaseProbability: 31,
    churnRisk: 76,
  },
  {
    id: "cli-biocentro",
    legalName: "Biocentro Especialidades S.A.",
    tradeName: "Biocentro",
    cuit: "30-70777741-9",
    address: "Godoy Cruz 421, Mendoza",
    province: "Mendoza",
    country: "Argentina",
    phone: "+54 261 490-0820",
    website: "https://biocentro.demo",
    taxCondition: "IVA Responsable Inscripto",
    type: "laboratorio",
    segment: "Especialidades regionales",
    status: "prospecto",
    executiveId: "usr-sofia",
    paymentTerms: "Contado",
    usualLeadTime: "18 dias",
    usualProducts: ["Prospectos medicos", "Etiquetas autoadhesivas"],
    priorityLevel: "C",
    commercialRisk: "moderado",
    internalNotes: "Necesita soporte cercano y visitas tecnicas.",
    lastInteractionAt: iso("2026-06-11T08:35:00"),
    nextAction: "Coordinar visita tecnica con calidad.",
    repurchaseProbability: 53,
    churnRisk: 34,
  },
  {
    id: "cli-neosynth",
    legalName: "NeoSynth Farma S.A.",
    tradeName: "NeoSynth",
    cuit: "30-71600661-3",
    address: "Ruta 2 km 49, Berazategui",
    province: "Buenos Aires",
    country: "Argentina",
    phone: "+54 11 4620-0185",
    website: "https://neosynth.demo",
    taxCondition: "IVA Responsable Inscripto",
    type: "laboratorio",
    segment: "Inyectables",
    status: "activo",
    executiveId: "usr-martin",
    paymentTerms: "60 dias",
    usualLeadTime: "25 dias",
    usualProducts: ["Etiquetas autoadhesivas", "Servicios especiales"],
    priorityLevel: "A",
    commercialRisk: "alto",
    internalNotes: "Cuenta critica por volumen y exigencia GMP.",
    lastInteractionAt: iso("2026-06-23T15:25:00"),
    nextAction: "Cerrar aprobacion gerencial de descuento especial.",
    repurchaseProbability: 74,
    churnRisk: 44,
  },
];

